services:
  wolds-hr-api:
    image: ${DOCKER_REGISTRY-}woldshrapi
    build:
      context: .
      dockerfile: wolds-hr-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_SYMMETRIC_SECURITY_KEY=${JWT_SYMMETRIC_SECURITY_KEY}
      - JWT_SETTINGS_REFRESH_TOKEN_EXPIRY_DAYS=${JWT_SETTINGS_REFRESH_TOKEN_EXPIRY_DAYS}
      - JWT_SETTINGS_REFRESH_TOKEN_TTL=${JWT_SETTINGS_REFRESH_TOKEN_TTL}
      - JWT_SETTINGS_RESET_PASSWORD_TOKEN_EXPIRY_DAYS=${JWT_SETTINGS_RESET_PASSWORD_TOKEN_EXPIRY_DAYS}
      - JWT_SETTINGS_TOKEN_EXPIRY_MINUTES=${JWT_SETTINGS_TOKEN_EXPIRY_MINUTES}
      - HOST_DOMAIN= ${HOST_DOMAIN}
    extra_hosts:
      - "host.docker.internal:host-gateway"