// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wolds_hr_api.Data.Context;

#nullable disable

namespace wolds_hr_api.Migrations
{
    [DbContext(typeof(WoldsHrDbContext))]
    partial class WoldsHrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wolds_hr_api.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("Verified")
                        .HasMaxLength(150)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WOLDS_HR_Account", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WOLDS_HR_Department", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Created")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ImportEmployeeHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ImportEmployeeHistoryId");

                    b.ToTable("WOLDS_HR_Employee", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeExistingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Created")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("EmployeeImportHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid?>("ImportEmployeeHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeImportHistoryId");

                    b.HasIndex("ImportEmployeeHistoryId");

                    b.ToTable("WOLDS_HR_ImportEmployeeExistingHistory", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeFailedErrorHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ImportEmployeeFailedHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImportEmployeeFailedHistoryId");

                    b.ToTable("WOLDS_HR_ImportEmployeeFailedErrorHistory", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeFailedHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ImportEmployeeHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImportEmployeeHistoryId");

                    b.ToTable("WOLDS_HR_ImportEmployeeFailedHistory", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("WOLDS_HR_ImportEmployeeHistory", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime");

                    b.Property<string>("ReplacedByToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("WOLDS_HR_RefreshToken", (string)null);
                });

            modelBuilder.Entity("wolds_hr_api.Domain.Employee", b =>
                {
                    b.HasOne("wolds_hr_api.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wolds_hr_api.Domain.ImportEmployeeHistory", "ImportEmployeeHistory")
                        .WithMany("ImportedEmployees")
                        .HasForeignKey("ImportEmployeeHistoryId");

                    b.Navigation("Department");

                    b.Navigation("ImportEmployeeHistory");
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeExistingHistory", b =>
                {
                    b.HasOne("wolds_hr_api.Domain.ImportEmployeeHistory", "EmployeeImportHistory")
                        .WithMany()
                        .HasForeignKey("EmployeeImportHistoryId");

                    b.HasOne("wolds_hr_api.Domain.ImportEmployeeHistory", null)
                        .WithMany("ExistingEmployees")
                        .HasForeignKey("ImportEmployeeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EmployeeImportHistory");
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeFailedErrorHistory", b =>
                {
                    b.HasOne("wolds_hr_api.Domain.ImportEmployeeFailedHistory", null)
                        .WithMany("Errors")
                        .HasForeignKey("ImportEmployeeFailedHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeFailedHistory", b =>
                {
                    b.HasOne("wolds_hr_api.Domain.ImportEmployeeHistory", null)
                        .WithMany("FailedEmployees")
                        .HasForeignKey("ImportEmployeeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wolds_hr_api.Domain.RefreshToken", b =>
                {
                    b.HasOne("wolds_hr_api.Domain.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("wolds_hr_api.Domain.Account", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeFailedHistory", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("wolds_hr_api.Domain.ImportEmployeeHistory", b =>
                {
                    b.Navigation("ExistingEmployees");

                    b.Navigation("FailedEmployees");

                    b.Navigation("ImportedEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
