name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: prodcrglobal.azurecr.io

      - name: Build and Push Docker image
        run: |
          docker build -t prodcrglobal.azurecr.io/prod-ap-wolds-hr-ct-api:latest .
          docker push prodcrglobal.azurecr.io/prod-ap-wolds-hr-ct-api:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: prodcrglobal.azurecr.io/prod-ap-wolds-hr-ct-api:latest
