name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: prodcrglobal.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |        
        docker build -f ./wolds-hr-api/Dockerfile -t prodcrglobal.azurecr.io/prod-ap-wolds-hr-ct-api:${{ github.sha }}
        docker push prodcrglobal.azurecr.io/prod-ap-wolds-hr-ct-api:${{ github.sha }}
